<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locations-upload [
    <!ELEMENT locations-upload (locations)>
    <!ATTLIST locations-upload operation (insert) "insert">
    <!ELEMENT locations (location+)>
    <!ELEMENT location (id?, name)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
]>
<locations-upload operation="insert">
    <locations>
        <location>
            <name>Coorparoo</name>
        </location>
        <location>
            <name>Riverhills</name>
        </location>
        <location>
            <name>Paddington</name>
        </location>
        <location>
            <name>Kangaroo Point</name>
        </location>
        <location>
            <name>Kelvin Grove</name>
        </location>
    </locations>
</locations-upload>
